fixed where i forgot to remove the using statement, Severity Code Description Project File Line Suppression State Error CS0246 The type or namespace name 'FileManagement' could not be found (are you missing a using directive or an assembly reference?) DTO D:\DTO_ML_RevitAddin\ExtDbAppEventLogger.cs 30 Active